[joomla]
192.168.56.14 ansible_user=vagrant ansible_ssh_private_key_file="/home/larissa/Documentos/projetos/joomla_ansible/.vagrant/machines/joomla/virtualbox/private_key"

[database]
192.168.56.12 ansible_user=vagrant ansible_ssh_private_key_file="/home/larissa/Documentos/projetos/joomla_ansible/.vagrant/machines/mysql/virtualbox/private_key"