
Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/focal64"
  
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
  
    config.vm.define "joomla" do |m|
      m.vm.network "private_network", ip: "192.168.56.14"
    end

    config.vm.box = "ubuntu/trusty64"

    config.vm.define "mysql" do |m|
      m.vm.network "private_network", ip: "192.168.56.12"
    end
  
  end
  